### ISSUE TITLE
url复制出来没有-t-的token

### ISSUE THREAD

**Issue by superZchen0701** [flytam/sz-vaccine#2]
如题，url如下：https://xgsz.szcdc.net/crmobile/?params=hYAPOVzzgsPD8XXKeSRfCMpL5WUhLA36+dt6T79HIpmDIhxM3tYSMhQ2nDYEbLhydvibLZEWMlwQjPIBt5SAsTkHKVEOS1TTaq4Zw2UyL5HHtDYkjxn0w3U0BQKzcV6FjFbBoUJsxSXmsTwX/yA0lIde5bfjcgJ/3/OwQQe39qGLvAEsDp2pPkgkKb6r1wTu3vcaqC4qQmMOZCp6rCxN4Q60LfalK5Z52I8aX7rzXbd8kGhazN2RF8zd+s2EX5R1hg70LjbdnWm5lEHfuOtKIvR2rbyYF4ERSzT+zcduD8FI6/yCYwc93iRp/7sUWkrr&selfAppId=wxde83a258df5775a1#/agreement

**Comment by flytam** [comment]
好像最近这里有变动了，F12打开控制台，输入`window.getUrlArgObject("token")`才能拿到token
![image](https://user-images.githubusercontent.com/20512530/120893876-017f5880-c648-11eb-955d-d4258b5ee20b.png)
